project:
  type: book
  output-dir: docs

book:
  title: "My-Thesis"
  subtitle: "Sous-titre optionnel"
  date: "17 mai 2025"
  author:
    name: "Nom Prénom"
  downloads: [pdf]  # Standard chapters list (used for PDF)
  chapters:
    - index.qmd  # Introduction with all frontmatter content
    - Chapters/Introduction.qmd
    - Chapters/Chapter1.qmd
    - Chapters/Chapter2.qmd
    - Chapters/Chapter3.qmd
    - Chapters/Chapter4.qmd
    - references.qmd
  appendices:
    - Appendices/AppendixA.qmd
    - Appendices/AppendixB.qmd
  site-url: https://nguyentruonganlab.github.io/quarto-thesis/
  search: true
  
  # Add repo URL for GitHub deployment
  repo-url: https://github.com/NguyenTruongAnLab/quarto-thesis
  repo-actions: [edit, issue]

# Bibliography style information
bibliography: [biblio/thesisrefs.bib, biblio/quarto.bib, biblio/packages.bib, biblio/pmf_refs.bib]
csl: biblio/american-statistical-association.csl

# Basic thesis information
degree: "Docteur de l'Université Grenoble Alpes"
submitted: 2025
defense_date: "17 mai 2025"
discipline: "Informatique"

# University information
university_name: "Université Grenoble Alpes"
university_logo: "images/logo.pdf" # Changed from logo.png to logo.pdf

# Department and organizational information
department: "Département d'Informatique"
faculty: "UFR IM2AG"
laboratory: "Laboratoire d'Informatique de Grenoble"
laboratory_address: "700 Avenue Centrale, 38400 Saint-Martin-d'Hères"

# Doctoral school information
doctoral_school: "MSTII"
doctoral_school_address: "110 rue de la Chimie, 38400 Saint-Martin-d'Hères"
thesis_number: "2025-UGA-123"

# Supervision
supervisor: "Prof. Jean Dupont"
co_supervisor: "Dr. Marie Lambert"
co_supervisor_2: "Dr. Jean Martin"
co_supervisor_3: "Dr. Sophie Leclerc"

# Committee members
committee_members: |
  \begin{tabular}{llcl}
      M. & Jean Dupont & \textit{Université Grenoble Alpes} & Directeur\\
      Mme. & Marie Curie & \textit{Université Paris-Saclay} & Rapportrice\\
      M. & Albert Einstein & \textit{CNRS}& Examinateur\\
      Mme. & Ada Lovelace & \textit{Université Grenoble Alpes} & Présidente\\
  \end{tabular


execute:
  freeze: auto # Changed from auto to true for stricter freezing
  echo: false
  warning: false   # Suppress all warning messages
  message: false   # Suppress all messages
  code-overflow: wrap
  python: ".venv/Scripts/python.exe"  # Use the virtual environment Python
  python-startup: "scripts/suppress_warnings.py"  # Load this script before running any Python code

format:
  html:
    theme: cosmo
    css: _extensions/quarto-thesis/html/custom-theme.scss
    page-layout: full
    html-math-method: mathjax
    toc: true
    toc-depth: 3
    toc-location: right
    toc-title: "On this page"
    toc-expand: true
    sidebar-width: 300px
    code-fold: true
    code-tools: true
    code-link: true
    embed-pdf: true  # Render PDF images as normal images
    fig-format: png # Ensure figures are generated in PNG format for HTML
  pdf:
    template-partials:
      - "_extensions/quarto-thesis/partials/before-body.tex"
      - "_extensions/quarto-thesis/partials/title.tex"
    include-in-header: 
      - "_extensions/quarto-thesis/partials/in-header.tex"
      - text: |
          \usepackage{booktabs}
          % Style for clean figure tables - remove all rules
          \newenvironment{cleanfiguretable}{%
            \renewcommand{\toprule}[1]{}%
            \renewcommand{\midrule}[1]{}%
            \renewcommand{\bottomrule}[1]{}%
          }{}
    documentclass: MastersDoctoralThesis
    use_custom_cover: false # true: use cover.pdf for the title page instead of defined information
    fig-format: pdf # Ensure figures are generated in PDF (vector) format
    toclinkcolor: black
    toc: false # Explicitly disable Quarto TOC for PDF since it's handled by the LaTeX template
    toc-depth: 2
    linkcolor: blue
    citecolor: blue
    urlcolor: blue
    link-citations: true
    
    # Additional debugging to see issues
    keep-tex: true
    
    # LaTeX compilation settings
    quiet: false
    progress: true
    latex-auto-install: true
    latex-min-runs: 3
    latex-max-runs: 12
    latex-clean: true
    
    # ONE-SIDED LAYOUT (for digital submission)
    classoption: ["oneside", "openany"]
    geometry: 
      - paper=a4paper
      - left=2.5cm
      - right=2.5cm
      - top=1.5cm
      - bottom=1.5cm
      - bindingoffset=0cm
    
    # TWO-SIDED LAYOUT (for printing) - uncomment these lines and comment out the above section
    # classoption: ["twoside", "openright"]
    # geometry: 
    #   - paper=a4paper
    #   - inner=3cm     # Slightly wider inner margin for binding
    #   - outer=2.5cm   # Reduced outer margin for balance
    #   - top=1.5cm
    #   - bottom=1.5cm
    #   - bindingoffset=0.5cm