project:
  type: book
  output-dir: _book

book:
  title: "Titre de la Thèse"
  subtitle: "Sous-titre optionnel"
  date: "17 mai 2025"
  author:
    name: "Nom Prénom"
  downloads: [pdf]  # Standard chapters list (used for PDF)
  chapters:
    - index.qmd
    - Chapters/Chapter1.qmd
    - Chapters/Chapter2.qmd
    - references.qmd
  appendices:
    - Appendices/AppendixA.qmd
  site-url: https://nguyentruonganlab.github.io/quarto-thesis/
  search: true
  
  # Add repo URL for GitHub deployment
  repo-url: https://github.com/NguyenTruongAnLab/quarto-thesis
  repo-actions: [edit, issue]

# Basic thesis information
degree: "Docteur de l'Université Grenoble Alpes"
submitted: 2025
defense_date: "17 mai 2025"
discipline: "Informatique"

# University information
university_name: "Université Grenoble Alpes"
university_logo: "images/logo.png"

# Department and organizational information
department: "Département d'Informatique"
faculty: "UFR IM2AG"
laboratory: "Laboratoire d'Informatique de Grenoble"
laboratory_address: "700 Avenue Centrale, 38400 Saint-Martin-d'Hères"

# Doctoral school information
doctoral_school: "MSTII"
doctoral_school_address: "110 rue de la Chimie, 38400 Saint-Martin-d'Hères"
thesis_number: "2025-UGA-123"

# Supervision
supervisor: "Prof. Jean Dupont"
co_supervisor: "Dr. Marie Lambert"
co_supervisor_2: "Dr. Jean Martin"
co_supervisor_3: "Dr. Sophie Leclerc"

# Committee members
committee_members: |
  \begin{tabular}{llcl}
      M. & Jean Dupont & \textit{Université Grenoble Alpes} & Directeur\\
      Mme. & Marie Curie & \textit{Université Paris-Saclay} & Rapportrice\\
      M. & Albert Einstein & \textit{CNRS}& Examinateur\\
      Mme. & Ada Lovelace & \textit{Université Grenoble Alpes} & Présidente\\
  \end{tabular}

thesis:
  # declaration: "Frontmatter/declaration.tex"
  abstract:
    english: "Frontmatter/abstract_en.tex"
    french: "Frontmatter/abstract_fr.tex"
  acknowledgements: "Frontmatter/acknowledgements.tex"
  abbreviations: "Frontmatter/abbreviations.tex"
  symbols: "Frontmatter/symbols.tex"
  dedication: "Frontmatter/dedication.tex"

bibliography: [example.bib]

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  html:
    theme: cosmo
    css: _extensions/quarto-thesis/html/custom-theme.scss
    page-layout: full
    html-math-method: mathjax
    toc: true
    toc-depth: 3
    toc-location: right
    toc-title: "On this page"
    toc-expand: true
    sidebar-width: 300px
    code-fold: true
    code-tools: true
    code-link: true
    # HTML-specific book structure
    book:
      chapters:
        - index.qmd
        - frontmatter/abstract-en.qmd
        - frontmatter/abstract-fr.qmd
        - frontmatter/acknowledgements.qmd
        - frontmatter/abbreviations.qmd
        - frontmatter/dedication.qmd
        - Chapters/Chapter1.qmd
        - Chapters/Chapter2.qmd
        - references.qmd
      appendices:
        - Appendices/AppendixA.qmd

  quarto-thesis-pdf:
    use_custom_cover: true
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2
    # The PDF will use the default chapters list defined above
    
    # ONE-SIDED LAYOUT (for digital submission)
    classoption: ["oneside", "openany"]
    geometry: 
      - paper=a4paper
      - left=2.5cm
      - right=2.5cm
      - top=1.5cm
      - bottom=1.5cm
      - bindingoffset=0cm
    
    # TWO-SIDED LAYOUT (for printing) - uncomment these lines and comment out the above section
    # classoption: ["twoside", "openright"]
    # geometry: 
    #   - paper=a4paper
    #   - inner=3cm     # Slightly wider inner margin for binding
    #   - outer=2.5cm   # Reduced outer margin for balance
    #   - top=1.5cm
    #   - bottom=1.5cm
    #   - bindingoffset=0.5cm