name: Create Release with PDF Thesis

on:
  push:
    branches:
      - main
    paths:
      - 'docs/Titre-de-la-Thèse.pdf'

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get current date and time
        id: datetime
        run: echo "datetime=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT
      
      - name: Copy PDF to root with version in name
        run: |
          mkdir -p release_assets
          cp "docs/Titre-de-la-Thèse.pdf" "release_assets/Thesis-v${{ steps.datetime.outputs.datetime }}.pdf"
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.datetime.outputs.datetime }}
          name: Thesis Version ${{ steps.datetime.outputs.datetime }}
          body: |
            Thesis version generated on ${{ steps.datetime.outputs.datetime }}
          files: |
            release_assets/Thesis-v${{ steps.datetime.outputs.datetime }}.pdf
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
